name: Build and deploy Node.js app to Azure Web App - LibraryWebWIN

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build,
        run: |
          npm install
          npm audit fix --force
          npm run build 

      - name: Archive production artifacts
        run: |
          mkdir -p build_output
          mv dist/librarymanagement.web build_output/
          tar -czf build_output.tar.gz -C build_output .
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: build_output.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Extract artifact
        run: tar -xzf build_output.tar.gz
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8632B4CAE37345B9B1541A3E20E21110 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_440DE5B9CB92422EBD1057058924B922 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9C7FF312F1C54C53AE7011BD372C8BB8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'LibraryWebWIN'
          slot-name: 'Production'
          package: .
